# Generated by Django 5.1.7 on 2025-03-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_external_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='company-logos')),
                ('description', models.TextField(max_length=2000)),
                ('website', models.URLField(blank=True, max_length=2083, null=True)),
                ('external_links', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/default_pfp.jpg', upload_to='profile_pics'),
        ),
    ]
