# Generated by Django 5.1.7 on 2025-03-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
