# Generated by Django 5.1.7 on 2025-03-12 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chats', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalClone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(max_length=500)),
                ('model', models.CharField(default='Llama3.1:8B', max_length=255)),
                ('mirostat', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('mirostat_eta', models.DecimalField(decimal_places=1, default=0.1, max_digits=2)),
                ('mirostat_tau', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('num_ctx', models.PositiveIntegerField(default=2048)),
                ('repeat_last_n', models.IntegerField(default=64)),
                ('repeat_penalty', models.DecimalField(decimal_places=1, default=1.1, max_digits=2)),
                ('temperature', models.DecimalField(decimal_places=1, default=0.8, max_digits=2)),
                ('seed', models.IntegerField(default=0)),
                ('top_p', models.DecimalField(decimal_places=1, default=0.9, max_digits=2)),
                ('min_p', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled knowledge base', max_length=255)),
                ('uuid', models.UUIDField()),
                ('active', models.BooleanField(default=False)),
                ('storage_size', models.IntegerField()),
                ('digital_clone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledgebases', to='messaging.digitalclone')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.chat')),
            ],
        ),
    ]
