INDUSTRY_CHOICES = [
    ("EDUCATION", "Education & Tutoring"),
    ("ACADEMIC_RESEARCH", "Academic Research"),
    ("STEM", "STEM (Science, Technology, Engineering, Math)"),
    ("BUSINESS", "Business & Entrepreneurship"),
    ("SOCIAL_SCIENCE", "Social Sciences"),
    ("HUMANITIES", "Humanities & Liberal Arts"),
    ("SOFTWARE", "Software Development"),
    ("AI", "Artificial Intelligence & Machine Learning"),
    ("ROBOTICS", "Robotics & Automation"),
    ("CYBERSECURITY", "Cybersecurity"),
    ("DATA_SCIENCE", "Data Science & Analytics"),
    ("BLOCKCHAIN", "Blockchain & Web3"),
    ("BIOTECH", "Biotechnology & Bioinformatics"),
    ("HARDWARE", "Hardware & Embedded Systems"),
    ("CLOUD_IT", "IT Services & Cloud Computing"),
    ("VR_AR", "Virtual Reality (VR) & Augmented Reality (AR)"),
    ("LIFE_SCIENCES", "Life Sciences & Biology"),
    ("CHEMISTRY", "Chemistry & Materials Science"),
    ("MEDICINE", "Medicine & Healthcare Innovation"),
    ("PHARMA", "Pharmaceuticals & Biotechnology"),
    ("NEUROSCIENCE", "Neuroscience"),
    ("ENVIRONMENTAL", "Environmental Science & Sustainability"),
    ("SPACE", "Space Science & Aerospace"),
    ("FINANCE", "Finance & Investing"),
    ("CONSULTING", "Management Consulting"),
    ("MARKETING", "Marketing & Advertising"),
    ("ECOMMERCE", "E-commerce & Retail"),
    ("REAL_ESTATE", "Real Estate & Urban Development"),
    ("SUPPLY_CHAIN", "Supply Chain & Logistics"),
    ("ENTREPRENEURSHIP", "Entrepreneurship & Startups"),
    ("JOURNALISM", "Journalism & Publishing"),
    ("PR", "Public Relations & Communications"),
    ("SOCIAL_MEDIA", "Social Media & Content Creation"),
    ("FILM", "Film & Television Production"),
    ("GRAPHIC_DESIGN", "Graphic Design & Visual Arts"),
    ("LAW", "Law & Legal Studies"),
    ("PUBLIC_POLICY", "Public Policy & Governance"),
    ("POLITICS", "Political Science & International Relations"),
    ("NGO", "Nonprofits & NGOs"),
    ("HUMAN_RIGHTS", "Human Rights & Advocacy"),
    ("ELECTRICAL_ENG", "Electrical & Electronics Engineering"),
    ("MECHANICAL_ENG", "Mechanical Engineering"),
    ("CIVIL_ENG", "Civil & Structural Engineering"),
    ("AEROSPACE_ENG", "Aerospace Engineering"),
    ("CHEMICAL_ENG", "Chemical Engineering"),
    ("RENEWABLE_ENERGY", "Renewable Energy & Sustainability"),
    ("SPORTS", "Sports & Athletic Training"),
    ("MENTAL_HEALTH", "Mental Health & Psychology"),
    ("PUBLIC_HEALTH", "Public Health & Epidemiology"),
    ("NUTRITION", "Nutrition & Dietetics"),
    ("MUSIC", "Music & Performing Arts"),
    ("PHILOSOPHY", "Philosophy & Ethics"),
    ("HISTORY", "History & Anthropology"),
    ("FASHION", "Fashion & Textile Design"),
]